### PR TITLE
Custom mapping at index creation

### LINKED ISSUE #394: Custom mapping with ElasticSearch
I am trying to use a custom mapping with easysearch:elasticsearch. First I set up an index like so:

``` javascript
index = new EasySearch.Index({
    collection: Books,
    fields: ['title'],
    engine: new EasySearch.ElasticSearch({
        client: {
            host: 'localhost:9200'
        }
    })
});
```

And I am trying to set up a custom mapping as is described in the docs like so:

``` javascript
index.config.elasticSearchClient.indices.putMapping({
        "index": "easysearch",
        "type": "books",
        "body": {
            "books": {
                "properties": {
                    "title": {
                        "type": "string",
                        "analyzer": "snowball"
                    }
                }
            }
        }
    });
```

However, when I do that, I get the following traceback:
`W20151212-13:21:35.732? (STDERR) Unhandled rejection Error: MergeMappingException[Merge failed with failures {[mapper [title] has different index_analyzer]}]
W20151212-13:21:35.732? (STDERR)     at respond (/Users/ilectrode/.meteor/packages/easysearch_elasticsearch/.2.0.3.1daznfj++os+web.browser+web.cordova/npm/node_modules/elasticsearch/src/lib/transport.js:256:15)
W20151212-13:21:35.733? (STDERR)     at checkRespForFailure (/Users/ilectrode/.meteor/packages/easysearch_elasticsearch/.2.0.3.1daznfj++os+web.browser+web.cordova/npm/node_modules/elasticsearch/src/lib/transport.js:219:7)
W20151212-13:21:35.733? (STDERR)     at HttpConnector.<anonymous> (/Users/ilectrode/.meteor/packages/easysearch_elasticsearch/.2.0.3.1daznfj++os+web.browser+web.cordova/npm/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
W20151212-13:21:35.733? (STDERR)     at IncomingMessage.wrapper (/Users/ilectrode/.meteor/packages/easysearch_elasticsearch/.2.0.3.1daznfj++os+web.browser+web.cordova/npm/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
W20151212-13:21:35.733? (STDERR)     at IncomingMessage.emit (events.js:117:20)
W20151212-13:21:35.734? (STDERR)     at _stream_readable.js:944:16
W20151212-13:21:35.734? (STDERR)     at process._tickCallback (node.js:448:13)`

It looks like the default mapping set up by easysearch is conflicting with my custom mappings. I have read the docs and the tests, and tried everything else I could, and I am unable to resolve my issue. I feel like the documents for the elasticsearch section are incomplete compared to the rest of the docs. 

Some documentation for setting up custom mappings would be appreciated.

### PR DESCRIPTION
**Pull request by bompi88**
Adds mapping to the config, which will set the mapping before indexing. fixes #394

### CODE REVIEW

**Comment by bompi88** [comment]
@matteodem The mapping configuration seem to work, but I wonder if document type (name) is always defined?

**Comment by matteodem** [comment]
It should always be defined. This looks mergeable to me. 

Do you have a test app that you used to test this feature? I'd like to test it once before merging it.

**Comment by bompi88** [comment]
I'll create a test app within the week which will include both the mapping and aggregation functionality 👍

**Comment by bompi88** [comment]
@matteodem Test app is now available at https://github.com/bompi88/easy-search-leaderboard.

**Comment by matteodem** [comment]
Currently at work but will check out later tonight

**Comment by matteodem** [comment]
Great stuff, gonna merge!

**Pull request merged**
