### PR TITLE
Add param @index=@index into Template.contentBlock call

### PR DESCRIPTION
**Pull request by huguesbrunelle**
Hi,
Here is the change BUT I couldn't test if it works or not.
I read and try to install from packages folder in my project but I couldn't make it to work.
Maybe you know a better way to test a package locally from a fork?
Anyway, let me know if this was what you had in mind earlier this week.
Thanks for time,

### CODE REVIEW

**Comment by matteodem** [comment]
Hi hugues, thanks for submitting the PR. I'll test it as soon as I get to it

**Comment by huguesbrunelle** [comment]
Hi Matteo, Sure no problem, let me know as I see the tests failed :(

**Comment by huguesbrunelle** [comment]
Hi Matteo, Let me know as I am finishing the project by the end on January. Cheers

**Comment by matteodem** [comment]
@huguesbrunelle this PR doesn't work. Frankly I'm not sure how to add this feature

**Comment by huguesbrunelle** [comment]
@matteodem does this could help http://stackoverflow.com/questions/32728619/how-to-get-the-index-of-nested-each-in-meteor ?

**Comment by matteodem** [comment]
I'm sorry but I'm really busy these days. I'll try to reserve time this weekend though

**Comment by huguesbrunelle** [comment]
No problem @matteodem No pressure :)

**Pull request closed without merging**
