### PR TITLE
Added an option to check for a specific constructor of a collection

### PR DESCRIPTION
**Pull request by NitroBAY**
Answer to the issue #527, was one couldn't use a collection NOT based on Meteor.collections as when one create EasySearch index, EasySearch used to `check(config.collection, Meteor.Collection);` so I added a parameter specialCollection to EasySearch.Index called specialCollection which take a string as the name of the name of the class of the collection.
Instance :

```
// Instantiate a ground collection or whatever collection you want
localWorksheets = new Ground.Collection('worksheets');

  WorksheetsSearch = new EasySearch.Index({
    collection: localWorksheets,
    specialCollection: 'Ground.Collection',
});
```

And the collection is just working with EasySearch.

### CODE REVIEW

**Comment by matteodem** [comment]
Can you please revert all the directory name changes? shouldn't be a problem

**Comment by NitroBAY** [comment]
Yes, sorry I didn't see that.

**Comment by NitroBAY** [comment]
Hmm, I never did that it's weird. I'll change that by hand, weird ?

**Comment by matteodem** [comment]
it's fine, where are the actual code changes? Just so that I might transfer them into the core and tag you in the commit

**Comment by NitroBAY** [comment]
Sure, line [17/18](https://github.com/NitroBAY/meteor-easy-search/blame/af7b74bbe6e289014f3ec19281e3197f08fc6605/packages/easysearch_core/lib/core/index.js#L17)

**Comment by NitroBAY** [comment]
Too sad to hear that I couldn't properly participate to some Meteor open source projects and especially yours, which is really, really great by the way.

**Comment by matteodem** [comment]
Thanks! you can, I'll definitely tag you in the commit when I get to it

**Comment by matteodem** [comment]
This is now implemented with a `ignoreCollectionCheck` property

**Pull request closed without merging**
