### PR TITLE
Custom index name

### PR DESCRIPTION
**Pull request by bompi88**
Implements custom index name for elasticsearch. This PR is dependant on the aggregation and mapping PRs #601 . @matteodem I will need to modify this PR after the merge of the other two.

### CODE REVIEW

**Comment by matteodem** [comment]
has conflicts now

**Comment by matteodem** [comment]
I'd happily merge the first commit of this PR

**Comment by bompi88** [comment]
I'll fix this PR when I've finished #601 👍

**Comment by matteodem** [comment]
This has been implemented in the latest version

**Pull request closed without merging**
